# Set up the main Python to use for source distributions
language: python
python:
  - '3.6'
git:
  depth: 5
env:
  global:
  - PY35: cp35-cp35m
    PY36: cp36-cp36m
  - secure: RHvX8qdwhhiRHwCFe1TPNglZ3Z0IWi6DjXVw6JgNuRKBPmglNXIG44abZrIGpsFijnQ2ymvFBFKyeotsKJ1bMQQPQx2B2YfsoZmyRniR0981qzp+QKNPhkNALY1mR5kXrhI4/wwy2TB5l0RY4bCEnR3bXPi95t5B/HMKGOW37FgekbjwSP/fPnUEAC/T4RowxCnwJDLaJnB2kS/813c8DBcpeMvYYs8JcUijvMOwqdUYPkkYzcvP7324W+HWvIf0ul0TfLPCCZVGZSmmcRvifYHu5wpQnTEIyKiILBqIbgiISm829/6dnGdR7thpsv3vbtkcGJ7I9UShvINJQrdoJfGrbisAa8NwxfgzamuCy72kH7NU50D3ahFGJkK4Z2/7hY33/jeky6NF6DUnu2kYlmM2agrOCpdKYclEoN5Us4QQ88+r7m8oms/K+VDPgz8tHXxH5rdIDEVqderElUVDNK6AyZQBq5yfgGkAr5McarH97nQYg7aFdVOkVV20JObchfCUhyzzrHAp1QfkwCvGqMYsYtX8DLo0hNikT9yv/OR6kab5HyvzppdVuw+xSaSqMYKIIVGNuhbwSWrFjB+Of8Umm+1RmledPJXVLijQT1R09WyI6ZXTeI0ovr/P0InY0d7PK6IBs3Uz/AIlCPsdmduQs/fP4aJ+xZDOSRgjZSM=
# Build on 32 & 64-bit Linux systems
matrix:
  fast_finish: true
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32
# Install the docker image & wheel
install:
- docker pull $DOCKER_IMAGE
- pip install wheel
# Build a source distribution, then build and test the wheels
script:
- python setup.py sdist
- docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build_wheels.sh $PY34 $PY35 $PY36
# Install twine for uploading to PyPI
before_deploy:
- pip install twine
- ls dist/
deploy:
  provider: script
  script: travis/travis_deploy.sh
  on:
    tags: true
    branch: master
  skip_cleanup: true
